// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto2_Api.Datos;

#nullable disable

namespace Proyecto2Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto2_Api.Modelo.ProyectoModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cantidades")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProyectoModelos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Cantidades = 5,
                            Detalle = "Detalle de la Vista..",
                            FechaActualizacion = new DateTime(2023, 4, 25, 17, 9, 39, 152, DateTimeKind.Local).AddTicks(6686),
                            FechaCreacion = new DateTime(2023, 4, 25, 17, 9, 39, 152, DateTimeKind.Local).AddTicks(6669),
                            ImagenUrl = "",
                            MetrosCuadrados = 90,
                            Tarifa = 1500.0,
                            nombre = "Vista Panorámica"
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Cantidades = 1,
                            Detalle = "Detalle de la Vista..",
                            FechaActualizacion = new DateTime(2023, 4, 25, 17, 9, 39, 152, DateTimeKind.Local).AddTicks(6689),
                            FechaCreacion = new DateTime(2023, 4, 25, 17, 9, 39, 152, DateTimeKind.Local).AddTicks(6688),
                            ImagenUrl = "",
                            MetrosCuadrados = 140,
                            Tarifa = 5800.0,
                            nombre = "Vista Premiun Panorámica"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
